### PR TITLE
Fix/add users emergency

### LINKED ISSUE #105: Finalize Add Users To Tour
- [x] api/ui error handling
- [x]  user that was added to tour (that is not the tour creator) should be able to see that tour in their current tours and be able to edit/add to it.

### PR DESCRIPTION
**Pull request by tashiad**
### What Type of PR Is This?
- [ ] New Feature 
- [x] Bug Fix
- [ ] Testing
- [ ] Refactoring/Clean Up 

#### What does this branch do? 
* Adds conditional to add tour partners feature in Plan step of Tour Form so that a message displays to the UI rather than "nil" if the added user doesn't have emergency contact info yet.

#### Have you tested your branch? How?
Chrome/dev tools

#### Do all existing unit and integration tests pass? 
N/A

#### Does this branch require special installation steps? 
No

#### Related Issues:
closes #105

### CODE REVIEW

File: src/components/Form/Plan.tsx [hunk 1]
```diff
@@ -40,10 +40,14 @@ export const Plan: React.FC<PlanProps> = ({
       return (
         <div key={i}>
           <h4>{user.name}</h4>
-          <p>
-            Emergency Contact: <br />
-            {user.emergency_contact_name} - {user.emergency_number}
-          </p>
+          <p>Emergency Contact:</p>
```
Comment (rachelbuchta) [inline src/components/Form/Plan.tsx:43]: Solid addition as far as user experience!

**Comment by rachelbuchta** [comment]
Way more informative for the user than "nil" ha. Thanks Tashia!
