### PR TITLE
Fix/cypress auth0

### LINKED ISSUE #48: Auth0 Cypress Updates
Test User:

BCBTestUser@gmail.com
BCBtest123!

### PR DESCRIPTION
**Pull request by tashiad**
### What Type of PR Is This?
- [x] New Feature 
- [x] Bug Fix
- [x] Testing
- [ ] Refactoring/Clean Up 

#### What does this branch do? 
Updates Cypress tests to pass since we've added Auth0 to the application.

#### Have you tested your branch? How?
Yes--all tests passing in Cypress

#### Do all existing unit and integration tests pass? 
Yes

#### Does this branch require special installation steps? 
No

#### Related Issues:
Closes #48 

There might be a more efficient way to write these tests so that we don't get a ton of logins for our test user but I think this works for now.

### CODE REVIEW

File: cypress/integration/current_tours_spec.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
+describe("Current Tours", () => {
+  const baseUrl = "http://localhost:3000"
+  const toursUrl = "http://localhost:3000/current-tours"
+
+  const logOut = () => {
```
Comment (rachelbuchta) [inline cypress/integration/current_tours_spec.js:5]: This is a good workaround and having it pulled out into this function makes it much more readable!

**Review by rachelbuchta — APPROVED** [review]
